name: Testbox
on:
  workflow_dispatch:
    inputs:
      testbox_id:
        description: "Testbox ID"
        required: true

jobs:
  testbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: useblacksmith/testbox@v1
      - run: |
          echo "Hello from Blacksmith Testbox!"
          uname -a
          pwd
          ls -la
